# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 57f75beb193865bb77b89a1b02bb4cbd3804655cacfab7709884e0a8f4b889eab4934668c06fba6107f7ad554f227ad419fcfea5a746576faf0c71a5d3315a49

test:
  secret_key_base: 217f4b60a770f0f3f006f28c40e909269edca8ed106cffda37d6c78267bdefcedd2742881607da20e07a60163ec687b6d2a48b8bf5266499e40a5d8ab73510ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
